blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://discord.gg/NAczq2T9F8
    about: Ask the community for help
  - name: Discuss Feature Ideas
    url: https://discord.gg/NAczq2T9F8
    about: Share and discuss your ideas in our Discord first
