name: "Update Changelog"

on:
  release:
    types: [released]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Create changelog update branch
        run: |
          git checkout -b changelog-update-${{ github.event.release.name }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: changelog-update-${{ github.event.release.name }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update CHANGELOG for ${{ github.event.release.name }}
          body: |
            This PR updates the CHANGELOG.md with the latest release notes for version ${{ github.event.release.name }}.
          branch: changelog-update-${{ github.event.release.name }}
          base: main
          delete-branch: true
